/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace AgentPayGuard {
      
    export type PaymentIntentStruct = {owner: AddressLike, recipient: AddressLike, amount: BigNumberish, jobId: BytesLike, nonce: BigNumberish, expiry: BigNumberish}

    export type PaymentIntentStructOutput = [owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, expiry: bigint] & {owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, expiry: bigint }
  

    export type IntentStateStruct = {owner: AddressLike, recipient: AddressLike, amount: BigNumberish, jobId: BytesLike, nonce: BigNumberish, createdAt: BigNumberish, expiry: BigNumberish, timelockEndsAt: BigNumberish, disputeEndsAt: BigNumberish, claimed: boolean, finalized: boolean, canceled: boolean, disputed: boolean, evidenceHash: BytesLike}

    export type IntentStateStructOutput = [owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, createdAt: bigint, expiry: bigint, timelockEndsAt: bigint, disputeEndsAt: bigint, claimed: boolean, finalized: boolean, canceled: boolean, disputed: boolean, evidenceHash: string] & {owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, createdAt: bigint, expiry: bigint, timelockEndsAt: bigint, disputeEndsAt: bigint, claimed: boolean, finalized: boolean, canceled: boolean, disputed: boolean, evidenceHash: string }
  
    }

  export interface AgentPayGuardInterface extends Interface {
    getFunction(nameOrSignature: "PAYMENT_INTENT_TYPEHASH" | "allowedRecipient" | "availableBalance" | "cancelIntent" | "claimIntent" | "createIntent" | "deposit" | "deposited" | "disputeIntent" | "eip712Domain" | "finalizeIntent" | "getIntent" | "hashIntent" | "locked" | "policies" | "resolveDispute" | "setPolicy" | "setRecipientAllowed" | "usdc" | "usedNonce" | "withdraw"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Deposited" | "EIP712DomainChanged" | "IntentCanceled" | "IntentClaimed" | "IntentCreated" | "IntentDisputed" | "IntentFinalized" | "IntentResolved" | "PolicyUpdated" | "RecipientAllowed" | "Withdrawn"): EventFragment;

    encodeFunctionData(functionFragment: 'PAYMENT_INTENT_TYPEHASH', values?: undefined): string;
encodeFunctionData(functionFragment: 'allowedRecipient', values: [AddressLike, AddressLike]): string;
encodeFunctionData(functionFragment: 'availableBalance', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'cancelIntent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'claimIntent', values: [BytesLike, BytesLike]): string;
encodeFunctionData(functionFragment: 'createIntent', values: [AgentPayGuard.PaymentIntentStruct, BytesLike]): string;
encodeFunctionData(functionFragment: 'deposit', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'deposited', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'disputeIntent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'eip712Domain', values?: undefined): string;
encodeFunctionData(functionFragment: 'finalizeIntent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getIntent', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'hashIntent', values: [AgentPayGuard.PaymentIntentStruct]): string;
encodeFunctionData(functionFragment: 'locked', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'policies', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BytesLike, boolean]): string;
encodeFunctionData(functionFragment: 'setPolicy', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'setRecipientAllowed', values: [AddressLike, boolean]): string;
encodeFunctionData(functionFragment: 'usdc', values?: undefined): string;
encodeFunctionData(functionFragment: 'usedNonce', values: [AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'withdraw', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'PAYMENT_INTENT_TYPEHASH', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'allowedRecipient', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'availableBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'claimIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposit', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'deposited', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'disputeIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'eip712Domain', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'finalizeIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashIntent', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'locked', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'policies', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setPolicy', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setRecipientAllowed', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usdc', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'usedNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'withdraw', data: BytesLike): Result;
  }

  
    export namespace DepositedEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace EIP712DomainChangedEvent {
      export type InputTuple = [];
      export type OutputTuple = [];
      export interface OutputObject {};
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentCanceledEvent {
      export type InputTuple = [intentHash: BytesLike, owner: AddressLike];
      export type OutputTuple = [intentHash: string, owner: string];
      export interface OutputObject {intentHash: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentClaimedEvent {
      export type InputTuple = [intentHash: BytesLike, recipient: AddressLike, evidenceHash: BytesLike];
      export type OutputTuple = [intentHash: string, recipient: string, evidenceHash: string];
      export interface OutputObject {intentHash: string, recipient: string, evidenceHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentCreatedEvent {
      export type InputTuple = [intentHash: BytesLike, owner: AddressLike, recipient: AddressLike, amount: BigNumberish, jobId: BytesLike, nonce: BigNumberish, expiry: BigNumberish, timelockEndsAt: BigNumberish, disputeEndsAt: BigNumberish];
      export type OutputTuple = [intentHash: string, owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, expiry: bigint, timelockEndsAt: bigint, disputeEndsAt: bigint];
      export interface OutputObject {intentHash: string, owner: string, recipient: string, amount: bigint, jobId: string, nonce: bigint, expiry: bigint, timelockEndsAt: bigint, disputeEndsAt: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentDisputedEvent {
      export type InputTuple = [intentHash: BytesLike, owner: AddressLike];
      export type OutputTuple = [intentHash: string, owner: string];
      export interface OutputObject {intentHash: string, owner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentFinalizedEvent {
      export type InputTuple = [intentHash: BytesLike, owner: AddressLike, recipient: AddressLike, amount: BigNumberish];
      export type OutputTuple = [intentHash: string, owner: string, recipient: string, amount: bigint];
      export interface OutputObject {intentHash: string, owner: string, recipient: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace IntentResolvedEvent {
      export type InputTuple = [intentHash: BytesLike, owner: AddressLike, paidOut: boolean];
      export type OutputTuple = [intentHash: string, owner: string, paidOut: boolean];
      export interface OutputObject {intentHash: string, owner: string, paidOut: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PolicyUpdatedEvent {
      export type InputTuple = [owner: AddressLike, maxPerIntent: BigNumberish, timelockSeconds: BigNumberish, disputeWindowSeconds: BigNumberish];
      export type OutputTuple = [owner: string, maxPerIntent: bigint, timelockSeconds: bigint, disputeWindowSeconds: bigint];
      export interface OutputObject {owner: string, maxPerIntent: bigint, timelockSeconds: bigint, disputeWindowSeconds: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace RecipientAllowedEvent {
      export type InputTuple = [owner: AddressLike, recipient: AddressLike, allowed: boolean];
      export type OutputTuple = [owner: string, recipient: string, allowed: boolean];
      export interface OutputObject {owner: string, recipient: string, allowed: boolean };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WithdrawnEvent {
      export type InputTuple = [owner: AddressLike, amount: BigNumberish];
      export type OutputTuple = [owner: string, amount: bigint];
      export interface OutputObject {owner: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface AgentPayGuard extends BaseContract {
    
    connect(runner?: ContractRunner | null): AgentPayGuard;
    waitForDeployment(): Promise<this>;

    interface: AgentPayGuardInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    PAYMENT_INTENT_TYPEHASH: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    allowedRecipient: TypedContractMethod<
      [owner: AddressLike, recipient: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    availableBalance: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    cancelIntent: TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    claimIntent: TypedContractMethod<
      [intentHash: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    createIntent: TypedContractMethod<
      [intent: AgentPayGuard.PaymentIntentStruct, signature: BytesLike, ],
      [string],
      'nonpayable'
    >
    

    
    deposit: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    deposited: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    disputeIntent: TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    eip712Domain: TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >
    

    
    finalizeIntent: TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >
    

    
    getIntent: TypedContractMethod<
      [intentHash: BytesLike, ],
      [AgentPayGuard.IntentStateStructOutput],
      'view'
    >
    

    
    hashIntent: TypedContractMethod<
      [intent: AgentPayGuard.PaymentIntentStruct, ],
      [string],
      'view'
    >
    

    
    locked: TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >
    

    
    policies: TypedContractMethod<
      [owner: AddressLike, ],
      [[bigint, bigint, bigint] & {maxPerIntent: bigint, timelockSeconds: bigint, disputeWindowSeconds: bigint }],
      'view'
    >
    

    
    resolveDispute: TypedContractMethod<
      [intentHash: BytesLike, payOut: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    setPolicy: TypedContractMethod<
      [maxPerIntent: BigNumberish, timelockSeconds: BigNumberish, disputeWindowSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    setRecipientAllowed: TypedContractMethod<
      [recipient: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >
    

    
    usdc: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    usedNonce: TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >
    

    
    withdraw: TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'PAYMENT_INTENT_TYPEHASH'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'allowedRecipient'): TypedContractMethod<
      [owner: AddressLike, recipient: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'availableBalance'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'cancelIntent'): TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'claimIntent'): TypedContractMethod<
      [intentHash: BytesLike, evidenceHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createIntent'): TypedContractMethod<
      [intent: AgentPayGuard.PaymentIntentStruct, signature: BytesLike, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposit'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'deposited'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'disputeIntent'): TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'eip712Domain'): TypedContractMethod<
      [],
      [[string, string, string, bigint, string, string, bigint[]] & {fields: string, name: string, version: string, chainId: bigint, verifyingContract: string, salt: string, extensions: bigint[] }],
      'view'
    >;
getFunction(nameOrSignature: 'finalizeIntent'): TypedContractMethod<
      [intentHash: BytesLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getIntent'): TypedContractMethod<
      [intentHash: BytesLike, ],
      [AgentPayGuard.IntentStateStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'hashIntent'): TypedContractMethod<
      [intent: AgentPayGuard.PaymentIntentStruct, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'locked'): TypedContractMethod<
      [owner: AddressLike, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'policies'): TypedContractMethod<
      [owner: AddressLike, ],
      [[bigint, bigint, bigint] & {maxPerIntent: bigint, timelockSeconds: bigint, disputeWindowSeconds: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [intentHash: BytesLike, payOut: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setPolicy'): TypedContractMethod<
      [maxPerIntent: BigNumberish, timelockSeconds: BigNumberish, disputeWindowSeconds: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setRecipientAllowed'): TypedContractMethod<
      [recipient: AddressLike, allowed: boolean, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'usdc'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'usedNonce'): TypedContractMethod<
      [owner: AddressLike, nonce: BigNumberish, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'withdraw'): TypedContractMethod<
      [amount: BigNumberish, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Deposited'): TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
getEvent(key: 'EIP712DomainChanged'): TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
getEvent(key: 'IntentCanceled'): TypedContractEvent<IntentCanceledEvent.InputTuple, IntentCanceledEvent.OutputTuple, IntentCanceledEvent.OutputObject>;
getEvent(key: 'IntentClaimed'): TypedContractEvent<IntentClaimedEvent.InputTuple, IntentClaimedEvent.OutputTuple, IntentClaimedEvent.OutputObject>;
getEvent(key: 'IntentCreated'): TypedContractEvent<IntentCreatedEvent.InputTuple, IntentCreatedEvent.OutputTuple, IntentCreatedEvent.OutputObject>;
getEvent(key: 'IntentDisputed'): TypedContractEvent<IntentDisputedEvent.InputTuple, IntentDisputedEvent.OutputTuple, IntentDisputedEvent.OutputObject>;
getEvent(key: 'IntentFinalized'): TypedContractEvent<IntentFinalizedEvent.InputTuple, IntentFinalizedEvent.OutputTuple, IntentFinalizedEvent.OutputObject>;
getEvent(key: 'IntentResolved'): TypedContractEvent<IntentResolvedEvent.InputTuple, IntentResolvedEvent.OutputTuple, IntentResolvedEvent.OutputObject>;
getEvent(key: 'PolicyUpdated'): TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
getEvent(key: 'RecipientAllowed'): TypedContractEvent<RecipientAllowedEvent.InputTuple, RecipientAllowedEvent.OutputTuple, RecipientAllowedEvent.OutputObject>;
getEvent(key: 'Withdrawn'): TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;

    filters: {
      
      'Deposited(address,uint256)': TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
      Deposited: TypedContractEvent<DepositedEvent.InputTuple, DepositedEvent.OutputTuple, DepositedEvent.OutputObject>;
    

      'EIP712DomainChanged()': TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
      EIP712DomainChanged: TypedContractEvent<EIP712DomainChangedEvent.InputTuple, EIP712DomainChangedEvent.OutputTuple, EIP712DomainChangedEvent.OutputObject>;
    

      'IntentCanceled(bytes32,address)': TypedContractEvent<IntentCanceledEvent.InputTuple, IntentCanceledEvent.OutputTuple, IntentCanceledEvent.OutputObject>;
      IntentCanceled: TypedContractEvent<IntentCanceledEvent.InputTuple, IntentCanceledEvent.OutputTuple, IntentCanceledEvent.OutputObject>;
    

      'IntentClaimed(bytes32,address,bytes32)': TypedContractEvent<IntentClaimedEvent.InputTuple, IntentClaimedEvent.OutputTuple, IntentClaimedEvent.OutputObject>;
      IntentClaimed: TypedContractEvent<IntentClaimedEvent.InputTuple, IntentClaimedEvent.OutputTuple, IntentClaimedEvent.OutputObject>;
    

      'IntentCreated(bytes32,address,address,uint256,bytes32,uint256,uint48,uint48,uint48)': TypedContractEvent<IntentCreatedEvent.InputTuple, IntentCreatedEvent.OutputTuple, IntentCreatedEvent.OutputObject>;
      IntentCreated: TypedContractEvent<IntentCreatedEvent.InputTuple, IntentCreatedEvent.OutputTuple, IntentCreatedEvent.OutputObject>;
    

      'IntentDisputed(bytes32,address)': TypedContractEvent<IntentDisputedEvent.InputTuple, IntentDisputedEvent.OutputTuple, IntentDisputedEvent.OutputObject>;
      IntentDisputed: TypedContractEvent<IntentDisputedEvent.InputTuple, IntentDisputedEvent.OutputTuple, IntentDisputedEvent.OutputObject>;
    

      'IntentFinalized(bytes32,address,address,uint256)': TypedContractEvent<IntentFinalizedEvent.InputTuple, IntentFinalizedEvent.OutputTuple, IntentFinalizedEvent.OutputObject>;
      IntentFinalized: TypedContractEvent<IntentFinalizedEvent.InputTuple, IntentFinalizedEvent.OutputTuple, IntentFinalizedEvent.OutputObject>;
    

      'IntentResolved(bytes32,address,bool)': TypedContractEvent<IntentResolvedEvent.InputTuple, IntentResolvedEvent.OutputTuple, IntentResolvedEvent.OutputObject>;
      IntentResolved: TypedContractEvent<IntentResolvedEvent.InputTuple, IntentResolvedEvent.OutputTuple, IntentResolvedEvent.OutputObject>;
    

      'PolicyUpdated(address,uint256,uint48,uint48)': TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
      PolicyUpdated: TypedContractEvent<PolicyUpdatedEvent.InputTuple, PolicyUpdatedEvent.OutputTuple, PolicyUpdatedEvent.OutputObject>;
    

      'RecipientAllowed(address,address,bool)': TypedContractEvent<RecipientAllowedEvent.InputTuple, RecipientAllowedEvent.OutputTuple, RecipientAllowedEvent.OutputObject>;
      RecipientAllowed: TypedContractEvent<RecipientAllowedEvent.InputTuple, RecipientAllowedEvent.OutputTuple, RecipientAllowedEvent.OutputObject>;
    

      'Withdrawn(address,uint256)': TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
      Withdrawn: TypedContractEvent<WithdrawnEvent.InputTuple, WithdrawnEvent.OutputTuple, WithdrawnEvent.OutputObject>;
    
    };
  }